server:
  port: 8081
spring:
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:data/schema.sql
      data-locations: classpath:data/data.sql

  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: imikasa.com
mybatis:
  mapper-locations: classpath:mapper/*.xml
